controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


app_admin_editHoraire:
    path: '/admin/horaires/edit/{id}'
    controller: 'App\Controller\YourController::editHoraire'
    methods: ['PUT']