# config/services.yaml
parameters:
    admin_email: 'arcadia.bretagne@gmail.com'
    env(MONGODB_URL): ''
    env(MONGODB_DB): ''
    
services:
    # Default configuration for services in this file
    _defaults:
        autowire: true      # Enable autowiring for all services
        autoconfigure: true # Automatically register services as commands, event subscribers, etc.

    # Makes classes in src/ available to be used as services
    # This creates a service per class whose ID is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Configure the MailerService
    App\Service\MailerService:
        arguments:
            $adminEmail: '%admin_email%'
            $mailer: '@Symfony\Component\Mailer\MailerInterface'

    # Enable autowiring for the Sanitizer service
    App\Service\Sanitizer:
        autowire: true
