-- Créer la DB
CREATE DATABASE IF NOT EXISTS arcadia_db
-- Utiliser la DB
USE arcadia_db

-- Créer les tables
CREATE TABLE IF NOT EXISTS animal (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    habitat_id INT DEFAULT NULL,
    prenom VARCHAR(255) NOT NULL,
    race VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    image_name VARCHAR(255) DEFAULT NULL,
    CONSTRAINT FK_6AAB231FAFFE2D26 FOREIGN KEY (habitat_id) REFERENCES habitat (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS avis (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    pseudo VARCHAR(255) NOT NULL,
    avis_content VARCHAR(512) NOT NULL,
    note INT NOT NULL,
    validation TINYINT(1) NOT NULL,
    created_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS habitat (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    image_name VARCHAR(255) DEFAULT NULL,
    description VARCHAR(4096) NOT NULL,
    updated_at DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS horaire (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    jour VARCHAR(8) NOT NULL,
    h_ouverture TIME NOT NULL,
    h_fermeture TIME NOT NULL,
    ouvert TINYINT(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS service (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    zoo_id INT DEFAULT NULL,
    nom VARCHAR(128) NOT NULL,
    description LONGTEXT NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    image_name VARCHAR(255) DEFAULT NULL,
    CONSTRAINT FK_E19D9AD2FA5C94EF FOREIGN KEY (zoo_id) REFERENCES zoo (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS user (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    email VARCHAR(180) NOT NULL,
    roles JSON NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    UNIQUE INDEX UNIQ_8D93D649E7927C74 (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS zoo (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    uuid CHAR(36) NOT NULL,
    nom VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ajotuer les contraintes
ALTER TABLE commentaire_habitat
    ADD CONSTRAINT FK_48FF20BBAFFE2D26 FOREIGN KEY (habitat_id) REFERENCES habitat (id),
    ADD CONSTRAINT FK_48FF20BB60BB6FE6 FOREIGN KEY (auteur_id) REFERENCES user (id);

ALTER TABLE info_animal
    ADD CONSTRAINT FK_A7767C4998BD5834 FOREIGN KEY (nourriture_id) REFERENCES nourriture (id),
    ADD CONSTRAINT FK_A7767C498E962C16 FOREIGN KEY (animal_id) REFERENCES animal (id),
    ADD CONSTRAINT FK_A7767C4960BB6FE6 FOREIGN KEY (auteur_id) REFERENCES user (id);

ALTER TABLE repas
    ADD CONSTRAINT FK_A8D351B398BD5834 FOREIGN KEY (nourriture_id) REFERENCES nourriture (id),
    ADD CONSTRAINT FK_A8D351B38E962C16 FOREIGN KEY (animal_id) REFERENCES animal (id);
