name: CD
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      SSHPASS: ${{ secrets.SSHPASS }}

    steps: 
      - uses: actions/checkout@v2
      
      - name: Install sshpass & update apt 
        run: |
          sudo apt update
          sudo apt install sshpass


      - name: deploy
        run: |
          sshpass -e ssh -o strictHostKeyChecking=no -p $SSHPASS ${{ secrets.SSH_USER}}@${{ secrets.SSH_IP}} 
