name: CD
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      SSHPASS: ${{ secrets.SSHPASS }}

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install sshpass & update apt 
        run: |
          sudo apt update
          sudo apt install sshpass
        
      - name: Deploy application
        run: |
          sshpass -e ssh -o strictHostKeyChecking=no  ${{ secrets.SSH_USER}}@${{ secrets.SSH_IP}} "
          git config --global --add safe.directory /home/arcadia-zoo/htdocs/arcadia-zoo.online
          cd /home/arcadia-zoo/htdocs/arcadia-zoo.online &&
          git pull https://github.com/Sebastien35/Arcadia.git &&
          composer install
          "

      
#deploy test
