name: CD
on:
  push:
    branches:
      - main
      - dev 
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      SSHPASS: ${{ secrets.SSHPASS }} #avc

    steps: 
      - uses: actions/checkout@v2
      
      - name: Install sshpass & update apt 
        run: |
          sudo apt update
          sudo apt install sshpass

      - name: deploy
        run: |
          sshpass -e ssh -o strictHostKeyChecking=no  root@${{secrets.SSH_IP}} "cd www/ && git pull origin main && composer install"
