name: CD
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      SSHPASS: ${{ secrets.SSHPASS }}

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install sshpass & update apt 
        run: |
          sudo apt update
          sudo apt install sshpass
        
      - name: Deploy application
        run: |
          sshpass -e ssh -o strictHostKeyChecking=no  ${{ secrets.SSH_USER}}@${{ secrets.SSH_IP}} "
          cd htdocs &&
          cd arcadia-zoo.online/ &&
          cd Arcadia &&
          git pull origin main &&
          composer install
          "

      
#deploy test
